name: ðŸ§ Linux Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor Linux (target=editor)
            cache-name: linux-editor
            target: editor
            tests: false
            sconsflags: use_llvm=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no
            doc-test: false
            bin: "./bin/godot.linuxbsd.editor.double.x86_64.llvm"
            proj-conv: false
            artifact: true
            platform: linuxbsd

          - name: Editor Linux Libgodot (target=editor)
            cache-name: linux-editor-shared-library
            target: editor
            tests: false
            sconsflags: use_llvm=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no library_type=shared_library
            doc-test: false
            bin: "./bin/libgodot.linuxbsd.editor.double.x86_64.llvm.so"
            proj-conv: false
            artifact: true
            platform: linuxbsd

          - name: Editor Windows (target=editor)
            cache-name: windows-editor
            target: editor
            tests: false
            sconsflags: use_llvm=yes use_mingw=yes custom_modules=../vsk_modules precision=double deprecate=no
            doc-test: false
            bin: "./bin/godot.windows.editor.double.x86_64.llvm.exe"
            proj-conv: false
            artifact: true
            platform: windows

          - name: Editor Windows Libgodot (target=editor)
            cache-name: windows-editor-shared-library
            target: editor
            tests: false
            sconsflags: use_llvm=yes use_mingw=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no library_type=shared_library
            doc-test: false
            bin: "./bin/godot.windows.editor.double.x86_64.llvm.dll"
            proj-conv: false
            artifact: true
            platform: windows

          # - name: Editor with doubles and GCC sanitizers (target=editor, tests=yes, dev_build=yes, precision=double, use_asan=yes, use_ubsan=yes, linker=gold)
          #   cache-name: linux-editor-double-sanitizers
          #   target: editor
          #   tests: false
          #   sconsflags: dev_build=yes precision=double use_asan=yes use_ubsan=yes linker=gold
          #   proj-test: false
          #   # Can be turned off for PRs that intentionally break compat with godot-cpp,
          #   # until both the upstream PR and the matching godot-cpp changes are merged.
          #   godot-cpp-test: false
          #   bin: "./bin/godot.linuxbsd.editor.dev.double.x86_64.san"
          #   build-mono: false
          #   # Skip 2GiB artifact speeding up action.
          #   artifact: false
          #   platform: linuxbsd
          #
          # - name: Editor with clang sanitizers (target=editor, tests=yes, dev_build=yes, use_asan=yes, use_ubsan=yes, use_llvm=yes, linker=gold)
          #   cache-name: linux-editor-llvm-sanitizers
          #   target: editor
          #   tests: false
          #   sconsflags: dev_build=yes use_asan=yes use_ubsan=yes use_llvm=yes linker=gold
          #   bin: "./bin/godot.linuxbsd.editor.dev.x86_64.llvm.san"
          #   build-mono: false
          #   # Skip 2GiB artifact speeding up action.
          #   artifact: false
          #   platform: linuxbsd

          - name: Editor with clang sanitizers (target=editor, tests=yes, dev_build=yes, use_asan=yes, use_ubsan=yes, use_llvm=yes, linker=gold)
            cache-name: linux-editor-llvm-sanitizers
            target: editor
            tests: true
            sconsflags: dev_build=yes use_asan=yes use_ubsan=yes use_llvm=yes linker=gold
            bin: "./bin/godot.linuxbsd.editor.dev.x86_64.llvm.san"
            build-mono: false
            # Skip 2GiB artifact speeding up action.
            artifact: false
            platform: linuxbsd

          - name: Minimal template (target=template_release, everything disabled, linker=gold)
            cache-name: linux-template-minimal
            target: template_release
            tests: false
            sconsflags: modules_enabled_by_default=no disable_3d=yes disable_advanced_gui=yes deprecated=no minizip=no linker=gold
            artifact: true
            platform: linuxbsd

    steps:
      - uses: actions/checkout@v3

      # Need newer mesa for lavapipe to work properly.
      - name: Linux dependencies for tests
        if: ${{ matrix.proj-test }}
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo add-apt-repository ppa:kisak/kisak-mesa
          sudo apt-get install -qq mesa-vulkan-drivers binutils

      - name: Linux dependencies for gold linker
        run: |
          sudo apt-get install -qq binutils

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Set up .NET Sdk
        uses: actions/setup-dotnet@v2
        if: ${{ matrix.build-mono }}
        with:
          dotnet-version: "6.0.x"

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Generate C# glue
        if: ${{ matrix.build-mono }}
        run: |
          ./godot/${{ matrix.bin }} --headless --generate-mono-glue ./godot/modules/mono/glue || true

      - name: Build .NET solutions
        if: ${{ matrix.build-mono }}
        run: |
          ./godot/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./godot/bin --godot-platform=linuxbsd

      # Execute unit tests for the editor
      - name: Unit tests
        if: ${{ matrix.tests }}
        run: |
          ./godot/${{ matrix.bin }} --version
          ./godot/${{ matrix.bin }} --help
          ./godot/${{ matrix.bin }} --test --headless

      # Check class reference
      - name: Check for class reference updates
        if: ${{ matrix.doc-test }}
        run: |
          echo "Running --doctool to see if this changes the public API without updating the documentation."
          echo -e "If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.\n\n"
          ./godot/${{ matrix.bin }} --doctool --headless 2>&1 > /dev/null || true
          git diff --color --exit-code && ! git ls-files --others --exclude-standard | sed -e 's/^/New doc file missing in PR: /' | grep 'xml$'

      # Test 3.x -> 4.x project converter
      - name: Test project converter
        if: ${{ matrix.proj-conv }}
        run: |
          mkdir converter_test
          cd converter_test
          touch project.godot
          ../godot/${{ matrix.bin }} --headless --validate-conversion-3to4
          cd ..
          rm converter_test -rf

      # Download and extract zip archive with project, folder is renamed to be able to easy change used project
      - name: Download test project
        if: ${{ matrix.proj-test }}
        run: |
          wget https://github.com/godotengine/regression-test-project/archive/4.0.zip
          unzip 4.0.zip
          mv "regression-test-project-4.0" "test_project"

      # Editor is quite complicated piece of software, so it is easy to introduce bug here
      - name: Open and close editor (Vulkan)
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ./godot/${{ matrix.bin }} --audio-driver Dummy --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      - name: Open and close editor (GLES3)
        if: ${{ matrix.proj-test }}
        run: |
          DRI_PRIME=0 xvfb-run ./godot/${{ matrix.bin }} --audio-driver Dummy --rendering-driver opengl3 --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Run test project
      - name: Run project
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ./godot/${{ matrix.bin }} 40 --audio-driver Dummy --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Checkout godot-cpp
      - name: Checkout godot-cpp
        if: ${{ matrix.godot-cpp-test }}
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot-cpp
          submodules: "recursive"
          path: "godot-cpp"

      # Dump GDExtension interface and API
      - name: Dump GDExtension interface and API for godot-cpp build
        if: ${{ matrix.godot-cpp-test }}
        run: |
          ./godot/${{ matrix.bin }} --headless --dump-gdextension-interface --dump-extension-api
          cp -f gdextension_interface.h godot-cpp/gdextension/
          cp -f extension_api.json godot-cpp/gdextension/

      # Build godot-cpp test extension
      - name: Build godot-cpp test extension
        if: ${{ matrix.godot-cpp-test }}
        run: |
          cd godot-cpp/test
          scons target=template_debug dev_build=yes
          cd ../..

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          strip godot/bin/godot.* || true
          strip godot/bin/libgodot.* || true
          chmod +x godot/bin/godot.* || true
          chmod +x godot/bin/libgodot.* || true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
